[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo  --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.72.0"

[[plugins]]
package = "../"
  [plugins.inputs]
  debug = true

[[plugins]]
package = "@netlify/plugin-local-install-core"
